### ISSUE TITLE
Remove "bibliographie" paragraphe inside documents

### ISSUE THREAD

**Issue by ben69uaq** [ben69uaq/pdftotxt#1]
add "bibliographie" label in the list in `RemoveReferenceParagraphe.java`

**Comment by Cececuche** [comment]
et Bibliography

**Comment by Cececuche** [comment]
Autre appellation : 
[Marsaud - 2019 - Séquençage à haut débit - Outils et enjeux pour la.pdf](https://github.com/ben69uaq/pdftotxt/files/6406936/Marsaud.-.2019.-.Sequencage.a.haut.debit.-.Outils.et.enjeux.pour.la.pdf)
"Sources bibliographiques"
