### ISSUE TITLE
Table_des_Matières

### ISSUE THREAD

**Issue by Cececuche** [ben69uaq/pdftotxt#10]
J'ai une table des matières avec des lignes
[Gregis - 2017 - Etude et réalisation d'un système miniaturisé pour.pdf](https://github.com/ben69uaq/pdftotxt/files/6404568/Gregis.-.2017.-.Etude.et.realisation.d.un.systeme.miniaturise.pour.pdf)

**Comment by ben69uaq** [comment]
ce n'est pas un problème, tout ce qui est avant le titre "Introduction" est supprimé.  
dans le cas de ce document, la table des matière qui se situe avant l'introduction est supprimée
