### ISSUE TITLE
The documents ends with "Conclusion" after sanitizing

### ISSUE THREAD

**Issue by ben69uaq** [ben69uaq/pdftotxt#3]
[Cherif - 2006 - Des puces à protéinespeptides pour des applicatio.pdf](https://github.com/ben69uaq/pdftotxt/files/6401266/Cherif.-.2006.-.Des.puces.a.proteinespeptides.pour.des.applicatio.pdf)

**Comment by Cececuche** [comment]
Enlever tout ce qui se trouve après la conclusion : références, biblio..., mais aussi souvent "Acknowledgment" dans article anglais.
[Cai et Chen - 2006 - Anti-Angiogenic Cancer Therapy Based on Integrin α.pdf](https://github.com/ben69uaq/pdftotxt/files/6409387/Cai.et.Chen.-.2006.-.Anti-Angiogenic.Cancer.Therapy.Based.on.Integrin.pdf)

**Comment by ben69uaq** [comment]
le problème est corrigé, par contre il y a toujours un bout de table des matières au début
