### ISSUE TITLE
"References" are still visible after sanitizing

### ISSUE THREAD

**Issue by ben69uaq** [ben69uaq/pdftotxt#4]
[Auffan - 2007 - NANOPARTICULES D'OXYDES MÉTALLIQUES   RELATI.pdf](https://github.com/ben69uaq/pdftotxt/files/6401280/Auffan.-.2007.-.NANOPARTICULES.D.OXYDES.METALLIQUES.RELATI.pdf)

**Comment by Cececuche** [comment]
Oups
