### ISSUE TITLE
Table of contents are not well sanitized

### ISSUE THREAD

**Issue by Cececuche** [ben69uaq/pdftotxt#5]
Prévoir cas où les points sont espacés
[Goubault - Colloïdes magnétiques auto-organisation et applic.pdf](https://github.com/ben69uaq/pdftotxt/files/6401277/Goubault.-.Colloides.magnetiques.auto-organisation.et.applic.pdf)

**Comment by ben69uaq** [comment]
Fixed

Suppression du paragraphe "Table des matières"
[Goubault - Colloïdes magnétiques auto-organisation et applic.pdf](https://github.com/ben69uaq/pdftotxt/files/6401621/Goubault.-.Colloides.magnetiques.auto-organisation.et.applic.pdf)

Suppression des lignes contenant plus de 5 dots
[Coudert - 2014 - Sources actuelles et futures des médicaments.pdf](https://github.com/ben69uaq/pdftotxt/files/6401632/Coudert.-.2014.-.Sources.actuelles.et.futures.des.medicaments.pdf)
